# Generated by Django 4.2.13 on 2024-07-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='member_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(unique=True)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('books_allowed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentid', models.IntegerField(unique=True)),
                ('comments', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.member_records')),
            ],
        ),
        migrations.CreateModel(
            name='book_borrowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('time_extended', models.IntegerField(default=0)),
                ('bookid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_page.booklist')),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_page.member_records')),
            ],
        ),
    ]
